- name: Install psycopg2
  become: yes
  apt:
    name: python3-psycopg2
    update_cache: yes

- name: Add PostgreSQL12 repository
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main
    update_cache: no
    state: present

- name: Get GPG Key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL12
  become: yes
  apt:
    name: postgresql-12
    state: present
    update_cache: yes

- name: Get access to DB from outside of localhost
  become: yes
  lineinfile:
    dest: /etc/postgresql/12/main/postgresql.conf
    regexp: '^#listen_addresses = ''localhost'''
    line: 'listen_addresses = ''*'''
    state: present

- name: Copy pg_hba.conf to /etc/postgresql/12/main/
  become: true
  copy:
    src: ../files/pg_hba.conf 
    dest: /etc/postgresql/12/main/pg_hba.conf

- name: Start PostgeSQL service
  become: yes
  service:
    name: postgresql
    state: started

- name: Create DB
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ POSTGRESQL_DB }}"
    state: present

- name: Create user
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ POSTGRESQL_DB }}"
    name: "{{ POSTGRESQL_DB_USER }}"
    password: "{{ POSTGRESQL_DB_PASSWD }}"
    priv: ALL
    state: present

- name: Access User
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ POSTGRESQL_DB }}"
    role: "{{ POSTGRESQL_DB_USER }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE

- name: Copy Schema
  become: yes
  become_user: postgres
  copy:
    src: ../files/schema.sql
    dest: /tmp/schema.sql

- name: Create Schema
  become: yes
  become_user: postgres
  postgresql_query:
    db: "{{ POSTGRESQL_DB }}"
    path_to_script: /tmp/schema.sql
    as_single_query: FALSE

- name: Restart PostgeSQL service
  become: yes
  service:
    name: postgresql
    state: restarted
