##
## EPITECH PROJECT, 2022
## zappie
## File description:
## Makefile
##

all:
		chmod +x zappy_ai
		cp zappy_ai ../

clean:
		rm -f ../zappy_ai

fclean: clean

re: fclean all

.PHONY:	all clean fclean re