##
## EPITECH PROJECT, 2021
## My_Rpg
## File description:
## Makefile
##

all:
		make -C ./asm/ all
		make -C ./corewar/ all

clean:
		make -C ./asm/ clean
		make -C ./corewar/ clean

fclean: clean
		make -C ./asm/ fclean
		make -C ./corewar/ fclean

re: fclean all

.PHONY: all clean fclean re