#!/usr/bin/python3
##
## EPITECH PROJECT, 2021
## tests codes
## File description:
## 107transfer
##

import math
from sys import argv

def information():
    print("USAGE")
    print("\t\t./107transfer [num den]*")
    print("DESCRIPTION")
    print("\t\tnumerator\tpolynomial numerator defined by its coefficients")
    print("\t\tdenominator\tpolynomial denominator defined by its coefficients")

def calc_result(x, num, den, result):
    num_res = 0
    den_res = 0
    for i in range(len(num)):
        num_res += float(num[i]) * (x ** i)
    for i in range(len(den)):
        den_res += float(den[i]) * (x ** i)
    if den_res == 0:
        exit (84)
    result *= num_res / den_res
    return (result)

def calc():
    tab = []
    for i in range(len(argv[1:])):
        tab.append(argv[i + 1].split("*"))
    x = 0.0
    while (x <= 1.001):
        result = 1.0
        for i in range(0, len(tab), 2):
            result = calc_result(x, tab[i], tab[i + 1], result)
        print('{:.3f} -> {:.5f}'.format(x, result))
        x += 0.001


def transfer():
    if (len(argv) >= 2):
        if (argv[1] == "-h"):
            information()
            exit (0)
        calc()
    else:
        print("Wrong arguments")
        exit (84)

def main():
    try:
        transfer()
    except Exception as e:
        exit (84)

main()